add sys_getrandom, add stdin without condvar
rcore-os/zCore pull request #131
Opened 2020-08-07 01:53 UTC by wfly1998

2020-08-07 06:55 UTC, wfly1998 commented
代码没通过 `cargo clippy`，下次注意qwq

2020-08-07 07:12 UTC, wangrunji0408 requested changes
后续有修改直接 commit 到原分支 push 即可，force push 也可以，不需要另开新 PR 了。

2020-08-07 09:07 UTC, wangrunji0408 requested changes

2020-08-07 09:07 UTC, wangrunji0408 commented on linux-syscall/src/task.rs
> +    pub async fn sys_nanosleep(&self, deadline: Deadline) -> SysResult {
注意 Linux 和 Zircon 对这个系统调用的 API 定义是不一样的。
所以不要直接把 Zircon 的实现复制过来，只需要把原来的 `thread::sleep(...)` 替换成新的 `kernel_hal::sleep_until(...).await` 就好。

2020-08-07 15:13 UTC, yunwei37 commented
Maybe you can help us add more document and unit test for these syscalls?

2020-08-08 02:21 UTC, wfly1998 commented
> Maybe you can help us add more document and unit test for these syscalls?
> 
> 
> 
>  : )

Of course, but my main work is software transportation. Therefore, I will add necessary documents for syscalls to pass the check of `#[deny(missing_doc)]`. 

BTW, what I've finished is, for example, `sys_getrandom`, `sys_poll`, `sys_nanosleep`. Maybe it's complex to write unit tests for them. 

\_(:з」∠)\_

2020-08-08 14:52 UTC, wangrunji0408 commented
I think unit test is only necessary for objects. Syscall layer can be tested in the loader crate.

2020-08-08 15:23 UTC, yunwei37 commented
qwq....I just mean maybe we can write unit test in in the loader crate like this ? #132

2020-08-10 02:28 UTC, wangrunji0408 commented
> qwq....I just mean maybe we can write unit test in in the loader crate like this ? #132

Exactly!

2020-08-11 10:27 UTC, wangrunji0408 requested changes

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-loader/Cargo.toml
> +# rcore-fs-hostfs = { git = "https://github.com/rcore-os/rcore-fs", rev = "e17b27b", optional = true }
不用注释，直接删掉就好

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-object/Cargo.toml
> +# rcore-fs = { git = "https://github.com/rcore-os/rcore-fs", rev = "e17b27b" }
不用注释，直接删掉就好

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-object/src/process.rs
> +    pub inner: Mutex<LinuxProcessInner>,
inner 部分是私有的，通过函数对外暴露功能。在 `poll` 中应该使用 `get_file_like`。

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-syscall/src/file/poll.rs
> +                        .get(&FileDesc::from(poll.fd as usize))
使用 `proc.get_file_like()`

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-syscall/src/file/poll.rs
> +    fd: u32,
```suggestion
    fd: FileDesc,
```

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-syscall/src/file/poll.rs
> +                drop(proc);
在 zCore 中 `LinuxProcess` 被改成了并发对象（原来 `proc` 是个 `MutexGuard`），这个 `drop` 应该可以去掉了

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-syscall/src/file/poll.rs
> +            #[allow(clippy::drop_ref)]
这个可以去掉了

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-syscall/src/file/poll.rs
> +        let polls = ufds.read_array(nfds).unwrap();
```suggestion
        let polls = ufds.read_array(nfds)?;
```

2020-08-11 10:27 UTC, wangrunji0408 commented on linux-syscall/src/file/poll.rs
> +        timeout_msecs: usize,
有兴趣的话可以考虑实现一下 timeout，用 `select!`

2020-08-11 10:49 UTC, wfly1998 commented on linux-syscall/src/misc.rs
> +                }
上面那条不能回复，在这回复好了...

`nanosleep` 的参数改为 `UserInPrt<TimeSpec>` 的话，需要在 `kernel_hal` 里再添加一个使用 `TimeSpec` 来 sleep 的函数吗

2020-08-11 11:02 UTC, wfly1998 commented on linux-syscall/src/task.rs
> +    pub async fn sys_nanosleep(&self, deadline: Deadline) -> SysResult {
`nanosleep` 的参数改为 `UserInPrt<TimeSpec>` 的话，需要在 `kernel_hal` 里再添加一个使用 `TimeSpec` 来 sleep 的函数吗

2020-08-11 12:23 UTC, wangrunji0408 requested changes

2020-08-11 12:23 UTC, wangrunji0408 commented on linux-object/src/process.rs
> +pub struct LinuxProcessInner {
这个 pub 也可以去掉

2020-08-11 12:23 UTC, wangrunji0408 commented on linux-object/src/process.rs
> +    pub files: HashMap<FileDesc, Arc<dyn FileLike>>,
这个 pub 也可以去掉

2020-08-11 12:23 UTC, wangrunji0408 commented on linux-syscall/src/misc.rs
> +        mut old_limit: UserInOutPtr<RLimit>,
```suggestion
        mut old_limit: UserOutPtr<RLimit>,
```

2020-08-11 12:23 UTC, wangrunji0408 commented on linux-syscall/src/misc.rs
> +                old_limit.write(RLimit {
根据文档描述，`old_limit` 指针可以为空：

> If the old_limit argument is a not NULL, then a
> successful call to prlimit() places the previous soft and hard limits
> for resource in the rlimit structure pointed to by old_limit.
> -- [prlimit64(2) — Linux manual page](https://man7.org/linux/man-pages/man2/prlimit64.2.html)

所以应该用 `write_if_not_null`，下同

2020-08-11 12:23 UTC, wangrunji0408 commented on linux-syscall/src/misc.rs
> +    #[allow(clippy::not_unsafe_ptr_arg_deref)]
这个好像也可以删了？

2020-08-11 13:05 UTC, wangrunji0408 approved these changes
辛苦辛苦了😂

2020-08-11 13:05 UTC, merged

2020-08-11 13:11 UTC, wfly1998 commented
rjgg 也辛苦了

我还是要认真读代码啊，尽量少出这种问题

现在 push 之前会习惯性用 `cargo fmt` 和 `cargo clippy` 检查代码了，也算是有点进步x